package examples.pubhub.model;
// default package

// Generated Jul 8, 2017 3:58:01 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BookTags generated by hbm2java
 */
@Entity
@Table(name = "BOOK_TAGS")
public class BookTags implements java.io.Serializable {

	private static final long serialVersionUID = -4099843235322147574L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "BOOK_TAGS_SEQ")
	@SequenceGenerator(name = "BOOK_TAGS_SEQ", sequenceName = "BOOK_TAGS_SEQ", allocationSize = 1)
	@Column(name = "TAG_ID", unique = true, nullable = false)
	private long tagId;

	@Column(name = "TAG_NAME")
	private String tagName;

	@ManyToOne
	@JoinColumn(name = "ISBN_13")
	private Book books;

	public BookTags() {
	}

	public BookTags(long tagId, Book books, String tagName) {
		this.tagId = tagId;
		this.books = books;
		this.tagName = tagName;
	}

	public long getTagId() {
		return this.tagId;
	}

	public void setTagId(long tagId) {
		this.tagId = tagId;
	}

	public Book getBook() {
		return this.books;
	}

	public void setBook(Book books) {
		this.books = books;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

}
