package examples.pubhub.model;
// default package

// Generated Jul 8, 2017 3:58:01 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name = "CART_ITEM")
public class CartItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -565741416947156990L;
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CART_ITEM_SEQ")
	@SequenceGenerator(name = "CART_ITEM_SEQ", sequenceName = "CART_ITEM_SEQ", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne
	@JoinColumn(name = "BOOK_ID")
	private Book books;
	@ManyToOne
	@JoinColumn(name = "CART_ID")
	private ShoppingCart shoppingCart;
	@Column(name = "QUANTITY")
	private int quantity;
	@Column(name = "SUB_TOTAL")
	private BigDecimal subTotal;

	public CartItem() {
	}

	public CartItem(int id, int quantity) {
		this.id = id;
		this.quantity = quantity;
	}

	public CartItem(int id, Book books, ShoppingCart shoppingCart, int quantity, BigDecimal subTotal) {
		this.id = id;
		this.books = books;
		this.shoppingCart = shoppingCart;
		this.quantity = quantity;
		this.subTotal = subTotal;

	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Book getBooks() {
		return this.books;
	}

	public void setBooks(Book books) {
		this.books = books;
	}

	public ShoppingCart getShoppingCart() {
		return this.shoppingCart;
	}

	public void setShoppingCart(ShoppingCart shoppingCart) {
		this.shoppingCart = shoppingCart;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

}
