package examples.pubhub.model;
// Generated Aug 22, 2017 9:17:06 AM by Hibernate Tools 5.2.3.Final


import java.time.LocalDate;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Message generated by hbm2java
 */

@XmlRootElement
public class Message implements java.io.Serializable {

	
	private static final long serialVersionUID = -5522065105669739936L;
	private int messageid;
	private Author author;
	private int authorId; 
	private String toAuthor;
	private String content;
	private String messageAuthor;
	private LocalDate datecreated;

	public Message() {
	}

	public Message(int messageid) {
		this.messageid = messageid;
	}

	public Message(int messageid, Author author, String content, LocalDate datecreated) {
		this.messageid = messageid;
		this.author = author;
		this.content = content;
		this.datecreated = datecreated;
	}

	
	
	
	public Message(int messageid, int authorId, String toAuthor, String content, String messageAuthor,
			LocalDate datecreated) {
	
		this.messageid = messageid;
		this.authorId = authorId;
		this.toAuthor = toAuthor;
		this.content = content;
		this.messageAuthor = messageAuthor;
		this.datecreated = datecreated;
	}

	

	public Message(int messageid, Author author, String content, String messageAuthor, LocalDate datecreated) {
		super();
		this.messageid = messageid;
		this.author = author;
		this.content = content;
		this.messageAuthor = messageAuthor;
		this.datecreated = datecreated;
		
		
	}

	public Message(String content, String messageAuthor) {
		super();
		this.content = content;
		this.messageAuthor = messageAuthor;
	}

	public int getMessageid() {
		return this.messageid;
	}

	public void setMessageid(int messageid) {
		this.messageid = messageid;
	}

	
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	public int getAuthorId() {
		return authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}
	

	public String getToAuthor() {
		return toAuthor;
	}

	public void setToAuthor(String toAuthor) {
		this.toAuthor = toAuthor;
	}

	public LocalDate getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = LocalDate.now();
	}

	public String getMessageAuthor() {
		return messageAuthor;
	}

	public void setMessageAuthor(String messageAuthor) {
		this.messageAuthor = messageAuthor;
	}

}
