package examples.pubhub.model;
// default package

// Generated Jul 8, 2017 3:58:01 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PurchasedBooks generated by hbm2java
 */
@Entity
@Table(name = "PURCHASED_BOOKS")
public class PurchasedBooks implements java.io.Serializable {

	private static final long serialVersionUID = 3479462841849952241L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PURCHASED_BOOKS_SEQ")
	@SequenceGenerator(name = "PURCHASED_BOOKS_SEQ", sequenceName = "PURCHASED_BOOKS_SEQ", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;

	@Column(name = "UNIT_PRICE")
	private double price;

	@Column(name = "QUANTITY")
	private int quantity;

	@Column(name = "SUB_TOTAL")
	private BigDecimal subTotal;

	@ManyToOne
	@JoinColumn(name = "BOOK_ID")
	private Book books;

	@ManyToOne
	@JoinColumn(name = "ORDER_ID")
	private BookOrder bookorder;

	public PurchasedBooks() {
	}

	public PurchasedBooks(double price, int quantity, BigDecimal subTotal, Book books, BookOrder bookorder) {

		this.price = price;
		this.quantity = quantity;
		this.subTotal = subTotal;
		this.books = books;
		this.bookorder = bookorder;
	}

	public PurchasedBooks(double price, int quantity, BigDecimal subTotal, Book books) {
		this.price = price;
		this.quantity = quantity;
		this.subTotal = subTotal;
		this.books = books;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getSubTotal() {
		return subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

	public Book getBooks() {
		return books;
	}

	public void setBooks(Book books) {
		this.books = books;
	}

	public BookOrder getBookorder() {
		return bookorder;
	}

	public void setBookorder(BookOrder bookorder) {
		this.bookorder = bookorder;
	}

}
