package examples.pubhub.model;
// default package

// Generated Jul 8, 2017 3:58:01 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name = "SHOPPING_CART")
public class ShoppingCart implements java.io.Serializable {

	private static final long serialVersionUID = -7245532326074255325L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SHOPPING_CART_SEQ")
	@SequenceGenerator(name = "SHOPPING_CART_SEQ", sequenceName = "SHOPPING_CART_SEQ", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long id;

	@Column(name = "GRAND_TOTAL")
	private BigDecimal grandTotal;

	@ManyToOne
	@JoinColumn(name = "USERID")
	private Users users;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "shoppingCart")
	private Set<CartItem> cartItems = new HashSet<>();

	public ShoppingCart() {
	}

	public ShoppingCart(Long id, Users users) {
		this.id = id;
		this.users = users;
	}

	public ShoppingCart(Long id, Users users, BigDecimal grandTotal, Set<CartItem> cartItems) {
		this.id = id;
		this.users = users;
		this.grandTotal = grandTotal;
		this.cartItems = cartItems;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public BigDecimal getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(BigDecimal grandTotal) {
		this.grandTotal = grandTotal;
	}

	public Set<CartItem> getCartItems() {
		return this.cartItems;
	}

	public void setCartItems(Set<CartItem> cartItems) {
		this.cartItems = cartItems;
	}

}
