package examples.pubhub.model;
// Generated Aug 22, 2017 9:17:06 AM by Hibernate Tools 5.2.3.Final

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Subscriber generated by hbm2java
 */

@XmlRootElement
public class Subscriber  {

	
	private int subcriberid;
	private Author author;
	private String subscribername;

	public Subscriber() {
	}

	public Subscriber(int subcriberid, Author author, String subscribername) {
		super();
		this.subcriberid = subcriberid;
		this.author = author;
		this.subscribername = subscribername;
	}

	public int getSubcriberid() {
		return subcriberid;
	}

	public void setSubcriberid(int subcriberid) {
		this.subcriberid = subcriberid;
	}

	public Author getAuthor() {
		return author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public String getSubscribername() {
		return subscribername;
	}

	public void setSubscribername(String subscribername) {
		this.subscribername = subscribername;
	}

	@Override
	public String toString() {
		return "Subscriber [subcriberid=" + subcriberid + ", author=" + author + ", subscribername=" + subscribername
				+ "]";
	}

	
	
	

}
