--------------------------------------------------------
--  File created - Tuesday-January-30-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

  CREATE TABLE "DBNAME"."AUTHOR" 
   (	"AUTHORID" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"AUTHORNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTHOR_FILES
--------------------------------------------------------

  CREATE TABLE "DBNAME"."AUTHOR_FILES" 
   (	"ID" NUMBER, 
	"AUTHORID" NUMBER, 
	"PORTRAIT" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PORTRAIT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOOKS
--------------------------------------------------------

  CREATE TABLE "DBNAME"."BOOKS" 
   (	"ISBN_13" VARCHAR2(13 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"AUTHOR" VARCHAR2(80 BYTE), 
	"PUBLISH_DATE" DATE, 
	"PRICE" NUMBER(6,2), 
	"CONTENT" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOOK_ORDER
--------------------------------------------------------

  CREATE TABLE "DBNAME"."BOOK_ORDER" 
   (	"ID" NUMBER, 
	"USERID" VARCHAR2(13 BYTE), 
	"GRAND_TOTAL" NUMBER(19,2), 
	"TIMESTAMP" DATE, 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOOK_TAGS
--------------------------------------------------------

  CREATE TABLE "DBNAME"."BOOK_TAGS" 
   (	"TAG_ID" NUMBER(11,0), 
	"TAG_NAME" VARCHAR2(30 BYTE), 
	"ISBN_13" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART_ITEM
--------------------------------------------------------

  CREATE TABLE "DBNAME"."CART_ITEM" 
   (	"ID" NUMBER(*,0), 
	"CART_ID" NUMBER(*,0), 
	"BOOK_ID" VARCHAR2(13 BYTE), 
	"QUANTITY" NUMBER(*,0), 
	"SUB_TOTAL" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGE
--------------------------------------------------------

  CREATE TABLE "DBNAME"."MESSAGE" 
   (	"MESSAGEID" NUMBER, 
	"CONTENT" VARCHAR2(250 BYTE), 
	"DATECREATED" DATE, 
	"AUTHORID" NUMBER, 
	"MESSAGEAUTHOR" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PURCHASED_BOOKS
--------------------------------------------------------

  CREATE TABLE "DBNAME"."PURCHASED_BOOKS" 
   (	"ID" NUMBER(*,0), 
	"ORDER_ID" NUMBER(*,0), 
	"BOOK_ID" VARCHAR2(13 BYTE), 
	"QUANTITY" NUMBER(*,0), 
	"UNIT_PRICE" NUMBER(6,2), 
	"SUB_TOTAL" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "DBNAME"."ROLES" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"ROLENAME" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHOPPING_CART
--------------------------------------------------------

  CREATE TABLE "DBNAME"."SHOPPING_CART" 
   (	"ID" NUMBER(11,0), 
	"USERID" VARCHAR2(13 BYTE), 
	"GRAND_TOTAL" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIBER
--------------------------------------------------------

  CREATE TABLE "DBNAME"."SUBSCRIBER" 
   (	"SUBCRIBERID" NUMBER, 
	"SUBSCRIBERNAME" VARCHAR2(50 BYTE), 
	"AUTHORID" NUMBER, 
	"USERID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DBNAME"."USERS" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"FIRSTNAME" VARCHAR2(255 BYTE), 
	"LASTNAME" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence ANIMALS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."ANIMALS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ANIMALS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."ANIMALS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUTHOR_FILES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."AUTHOR_FILES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUTHOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."AUTHOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOOK_ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."BOOK_ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOOK_TAGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."BOOK_TAGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 142 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOOK_TAGS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."BOOK_TAGS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CART_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."CART_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."EVENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EZOO_ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."EZOO_ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EZOO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."EZOO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FEEDING_SCHEDULES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."FEEDING_SCHEDULES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HEALTH_PLAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."HEALTH_PLAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HEALTPLAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."HEALTPLAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MESSAGE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."MESSAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PURCHASED_BOOKS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."PURCHASED_BOOKS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOPPING_CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."SHOPPING_CART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUBSCRIBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."SUBSCRIBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TABLE1_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."TABLE1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DBNAME"."USERS_ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index AUTHOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."AUTHOR_PK" ON "DBNAME"."AUTHOR" ("AUTHORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTHOR_FILES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."AUTHOR_FILES_PK" ON "DBNAME"."AUTHOR_FILES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007088
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."SYS_C007088" ON "DBNAME"."BOOKS" ("ISBN_13") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOOK_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."BOOK_ORDER_PK" ON "DBNAME"."BOOK_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOOK_TAGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."BOOK_TAGS_PK" ON "DBNAME"."BOOK_TAGS" ("TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOOK_TAGS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."BOOK_TAGS_UK1" ON "DBNAME"."BOOK_TAGS" ("TAG_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CART_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."CART_ITEM_PK" ON "DBNAME"."CART_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MESSAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."MESSAGE_PK" ON "DBNAME"."MESSAGE" ("MESSAGEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PURCHASED_BOOKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."PURCHASED_BOOKS_PK" ON "DBNAME"."PURCHASED_BOOKS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_INDEX1
--------------------------------------------------------

  CREATE INDEX "DBNAME"."ROLES_INDEX1" ON "DBNAME"."ROLES" ("USERNAME", "ROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SHOPPING_CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."SHOPPING_CART_PK" ON "DBNAME"."SHOPPING_CART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."SUBSCRIBER_PK" ON "DBNAME"."SUBSCRIBER" ("SUBCRIBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBNAME"."USERS_PK" ON "DBNAME"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AUTHOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."AUTHOR_TRG" 
BEFORE INSERT ON AUTHOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."AUTHOR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTHOR_FILES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."AUTHOR_FILES_TRG" 
BEFORE INSERT ON AUTHOR_FILES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."AUTHOR_FILES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOOK_ORDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."BOOK_ORDER_TRG" 
BEFORE INSERT ON BOOK_ORDER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."BOOK_ORDER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOOK_TAGS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."BOOK_TAGS_TRG1" 
BEFORE INSERT ON BOOK_TAGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."BOOK_TAGS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOOK_TAGS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."BOOK_TAGS_TRG" 
BEFORE INSERT ON BOOK_TAGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TAG_ID IS NULL THEN
      SELECT BOOK_TAGS_SEQ.NEXTVAL INTO :NEW.TAG_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."BOOK_TAGS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOOK_TAGS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."BOOK_TAGS_TRG2" 
BEFORE INSERT ON BOOK_TAGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."BOOK_TAGS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CART_ITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."CART_ITEM_TRG" 
BEFORE INSERT ON CART_ITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CART_ITEM_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."CART_ITEM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."MESSAGE_TRG" 
BEFORE INSERT ON MESSAGE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MESSAGEID IS NULL THEN
      SELECT MESSAGE_SEQ.NEXTVAL INTO :NEW.MESSAGEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."MESSAGE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PURCHASED_BOOKS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."PURCHASED_BOOKS_TRG" 
BEFORE INSERT ON PURCHASED_BOOKS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PURCHASED_BOOKS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."PURCHASED_BOOKS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SHOPPING_CART_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."SHOPPING_CART_TRG" 
BEFORE INSERT ON SHOPPING_CART 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SHOPPING_CART_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."SHOPPING_CART_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUBSCRIBER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DBNAME"."SUBSCRIBER_TRG" 
BEFORE INSERT ON SUBSCRIBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DBNAME"."SUBSCRIBER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBNAME"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "DBNAME"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'N35ZGU2M9CXB2FAN89UFNSXB5KECPO';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  Constraints for Table AUTHOR
--------------------------------------------------------

  ALTER TABLE "DBNAME"."AUTHOR" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("AUTHORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."AUTHOR" MODIFY ("AUTHORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHOR_FILES
--------------------------------------------------------

  ALTER TABLE "DBNAME"."AUTHOR_FILES" ADD CONSTRAINT "AUTHOR_FILES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."AUTHOR_FILES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOKS
--------------------------------------------------------

  ALTER TABLE "DBNAME"."BOOKS" ADD PRIMARY KEY ("ISBN_13")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK_ORDER
--------------------------------------------------------

  ALTER TABLE "DBNAME"."BOOK_ORDER" ADD CONSTRAINT "BOOK_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."BOOK_ORDER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK_TAGS
--------------------------------------------------------

  ALTER TABLE "DBNAME"."BOOK_TAGS" ADD CONSTRAINT "BOOK_TAGS_UK1" UNIQUE ("TAG_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."BOOK_TAGS" MODIFY ("ISBN_13" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."BOOK_TAGS" ADD CONSTRAINT "BOOK_TAGS_PK" PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."BOOK_TAGS" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."BOOK_TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART_ITEM
--------------------------------------------------------

  ALTER TABLE "DBNAME"."CART_ITEM" ADD CONSTRAINT "CART_ITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."CART_ITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "DBNAME"."MESSAGE" ADD CONSTRAINT "MESSAGE_PK" PRIMARY KEY ("MESSAGEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."MESSAGE" MODIFY ("MESSAGEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASED_BOOKS
--------------------------------------------------------

  ALTER TABLE "DBNAME"."PURCHASED_BOOKS" ADD CONSTRAINT "PURCHASED_BOOKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."PURCHASED_BOOKS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "DBNAME"."ROLES" MODIFY ("ROLENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOPPING_CART
--------------------------------------------------------

  ALTER TABLE "DBNAME"."SHOPPING_CART" ADD CONSTRAINT "SHOPPING_CART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."SHOPPING_CART" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."SHOPPING_CART" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "DBNAME"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_PK" PRIMARY KEY ("SUBCRIBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."SUBSCRIBER" MODIFY ("SUBCRIBERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DBNAME"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AUTHOR
--------------------------------------------------------

  ALTER TABLE "DBNAME"."AUTHOR" ADD CONSTRAINT "AUTHOR_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "DBNAME"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTHOR_FILES
--------------------------------------------------------

  ALTER TABLE "DBNAME"."AUTHOR_FILES" ADD CONSTRAINT "AUTHOR_FILES_FK1" FOREIGN KEY ("AUTHORID")
	  REFERENCES "DBNAME"."AUTHOR" ("AUTHORID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK_ORDER
--------------------------------------------------------

  ALTER TABLE "DBNAME"."BOOK_ORDER" ADD CONSTRAINT "BOOK_ORDER_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "DBNAME"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK_TAGS
--------------------------------------------------------

  ALTER TABLE "DBNAME"."BOOK_TAGS" ADD CONSTRAINT "BOOK_TAGS_FK1" FOREIGN KEY ("ISBN_13")
	  REFERENCES "DBNAME"."BOOKS" ("ISBN_13") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART_ITEM
--------------------------------------------------------

  ALTER TABLE "DBNAME"."CART_ITEM" ADD CONSTRAINT "CART_ITEM_FK1" FOREIGN KEY ("CART_ID")
	  REFERENCES "DBNAME"."SHOPPING_CART" ("ID") ENABLE;
  ALTER TABLE "DBNAME"."CART_ITEM" ADD CONSTRAINT "CART_ITEM_FK2" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "DBNAME"."BOOKS" ("ISBN_13") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGE
--------------------------------------------------------

  ALTER TABLE "DBNAME"."MESSAGE" ADD CONSTRAINT "MESSAGE_FK1" FOREIGN KEY ("AUTHORID")
	  REFERENCES "DBNAME"."AUTHOR" ("AUTHORID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASED_BOOKS
--------------------------------------------------------

  ALTER TABLE "DBNAME"."PURCHASED_BOOKS" ADD CONSTRAINT "PURCHASED_BOOKS_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "DBNAME"."BOOK_ORDER" ("ID") ENABLE;
  ALTER TABLE "DBNAME"."PURCHASED_BOOKS" ADD CONSTRAINT "PURCHASED_BOOKS_FK2" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "DBNAME"."BOOKS" ("ISBN_13") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "DBNAME"."ROLES" ADD CONSTRAINT "ROLES_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "DBNAME"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOPPING_CART
--------------------------------------------------------

  ALTER TABLE "DBNAME"."SHOPPING_CART" ADD CONSTRAINT "SHOPPING_CART_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "DBNAME"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "DBNAME"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_FK1" FOREIGN KEY ("AUTHORID")
	  REFERENCES "DBNAME"."AUTHOR" ("AUTHORID") ENABLE;
  ALTER TABLE "DBNAME"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "DBNAME"."USERS" ("USERNAME") ON DELETE SET NULL ENABLE;
